### ISSUE TITLE
"algolia.css URI malformed" error

### ISSUE THREAD

**Issue by PaPa31** [lelouch77/docusaurus-lunr-search#45]
When I run `npm run build`, I get an error like this:

```shell
algolia.css

URI malformed at decodeURI (<anonymous>)
```

I temporarily fixed this by replacing the `background-image` property in the last declaration block `.algolia-autocomplete .algolia-docsearch-footer--logo` in the `algolia.css` file with this line:

```css title="algolia.css" {2}
.algolia-autocomplete .algolia-docsearch-footer--logo {
    background-image: url('data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAF8AAAAGCAYAAAClzULKAAAABHNCSVQICAgIfAhkiAAAACtJREFUSEtjZBgFAxYCjANm86jFDKOBP4CJYDTwRwN/AENgAK0eTfkDGPgAKC8ABxS+xFUAAAAASUVORK5CYII=');
    ...
```

While it works fine, but I wonder what the cause of the problem? And how to fix this error permanently?
